gammes:
  - nom: Gamme 1
    notes:
      - F#1
      - C#2
      - G#2
      - Eb3
      - G3
      - B3
      - D4
      - F4
      - Ab4
      - C5
      - Eb5
      - F5
      - G#5
      - Bb5
      - C6
      - C#6
      - D6
      - E#6
      - F6
      - F#6
  - nom: Gamme 2
    notes:
      - C1
      - D1
      - E1
      - F1
      - G1
      - A1
      - B1
      - C2
      - D2
      - E2
      - F2
      - G2
      - A2
      - B2
      - C3